# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Lint translation files

on:
  pull_request:
    branches: [ master, main, stable-* ]
  push:
    branches: [ master, main, stable-* ]

permissions:
  contents: read

concurrency:
  group: lint-php-cs-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest-low

    name: translations-string-xml

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Check for new lines in translation strings
        id: counter
        run: |
          grep -P '<string name' app/src/main/res/values/strings.xml | grep -vcP '</string>' | grep '^0$'

      - name: Output
        if: failure()
        run: |
          grep -P '<string name' app/src/main/res/values/strings.xml | grep -vP '</string>'
